inherit_from:
  - .rubocop_airbnb.yml

Rails:
  Enabled: true

AllCops:
  TargetRubyVersion: 2.6.3
  #以下にはrubocopで検証したくないフォルダを指定する
  Exclude:
    - 'db/**/*'
    - 'bin/*'
    - 'config/environments/*'
    - 'config/application.rb'
    - 'config/initializers/*'
    - 'config/spring.rb'
    - 'lib/tasks/*'
    - 'vendor/**/*'
    - 'node_modules/**/*'
    - 'path/ruby'
    - 'spec/spec_helper.rb'